### ISSUE TITLE
troublesome leap_hand_left.urdf

### ISSUE THREAD

**Issue by zhoubohan0** [dexsuite/dex-urdf#19]
Hi! About the left side of leap hand urdf, did you notice the collision of the mesh seems not that correct? This means, the thumb of leap hand left can not rotate freely and can easily get stuck with palm link. Is there any new version of leap hand urdf left?

**Comment by yzqin** [comment]
Hi @zhoubohan0 

Good catch, there is something wrong about the leap hand collision mesh for the left hand. Due to some issues in the original leap hand modeling, the left and right leap hand are not simply mirrored, which makes this problem not so easy to solve. I will fix it soon and let you know.

**Comment by yzqin** [comment]
hi @zhoubohan0 

This bug has been fixed in recent commits 99720cdf44f5c6564ef9fd208a7cbc8bdf65953d and 6eeda17435d46dde5915a16fd37b248bd8bb468e. 

If you still encounter some collision issues related to the left leap hand, feel free to open another issue.
