### ISSUE TITLE
Could you provide the UR10e assets corresponding to Sapien?

### ISSUE THREAD

**Issue by Charlie0257** [dexsuite/dex-urdf#4]
Hi, @yzqin,

Could you provide the UR10e assets corresponding to Sapien? When I load the UR10e assets from Isaacgym, they blow up but can run well in Isaacgym.

Could you help me solve the problem? Thanks for any questions :)

**Comment by yzqin** [comment]
The problem lies in the `dae` mesh model loaded in IsaacGym, such as your UR10e. It is enabled with a specific tag, `flip_visual_attachments=True`. This tag alters the definition of the up and forward axis as defined in the `dae` mesh. It only functions when `flip_visual_attachments=True` is set in IsaacGym. If this tag is set to False, it will cause problems. 

Also this problem will happen only if the mesh file is stored as `dae` file. `obj` and `stl` will not have such issue..

```python
asset_options = gymapi.AssetOptions()
asset_options.flip_visual_attachments = True
```

For other simulators like SAPIEN and PyBullet, they adhere to the original mesh, causing the mesh to break up.

We plan to rectify the model at the mesh level and soon make the UR10e + Shadow version publicly available in this repository.

**Comment by Charlie0257** [comment]
Thanks for your answer:)

I am looking forward to these models!

**Comment by yzqin** [comment]
See [ur10e model](https://github.com/dexsuite/dex-urdf/tree/main/robots/arms/ur10e) for more details, which is added in 24162c8dee868c2c2f9962bf2dbeb0ca48834c54

**Comment by Charlie0257** [comment]
@yzqin Thanks for providing the assets! I will close this issue.
Hope to keep in touch:)
